# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: |
    pip install -U platformio
    platformio update
  displayName: 'get platform IO'

- script: |
    platformio run
  displayName: 'Build firmware'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.SourcesDirectory)/.pio/build/esp01_1m/
    Contents: '*.bin'
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Firmware $(Build.BuildNumber)'
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    publishLocation: Container
    TargetPath: .
